var overviewerConfig = {
    "CONST": {
        "tileSize": 384,
        "image": {
            "defaultMarker": "signpost.png",
            "signMarker": "signpost_icon.png",
            "bedMarker": "bed.png",
            "spawnMarker": "markers/marker_home.png",
            "spawnMarker2x": "markers/marker_home_2x.png",
            "queryMarker": "markers/marker_location.png",
            "queryMarker2x": "markers/marker_location_2x.png",
            "compass": {
                "0": "compass_upper-left.png",
                "1": "compass_upper-right.png",
                "3": "compass_lower-left.png",
                "2": "compass_lower-right.png"
            }
        },
        "mapDivId": "mcmap",
        "UPPERLEFT": 0,
        "UPPERRIGHT": 1,
        "LOWERLEFT": 3,
        "LOWERRIGHT": 2
    },
    "worlds": [
        "Bulbasaur",
        "Ivysaur",
        "Venusaur",
        "Charmander",
        "Charmeleon",
        "Charizard",
        "Squirtle",
        "Wartortle",
        "Blastoise",
        "Caterpie",
        "Metapod",
        "Butterfree",
        "Weedle",
        "Kakuna",
        "Beedrill",
        "Pidgey",
        "Pidgeotto",
        "Pidgeot",
        "Rattata",
        "Raticate",
        "Spearow",
        "Fearow",
        "Ekans",
        "Arbok",
        "Pikachu",
        "Raichu",
        "Sandshrew",
        "Sandslash",
        "NidoranF",
        "Nidorina",
        "Nidoqueen",
        "NidoranM",
        "Nidorino",
        "Nidoking",
        "Clefairy",
        "Clefable",
        "Vulpix",
        "Ninetales",
        "Jigglypuff",
        "Wigglytuff",
        "Zubat",
        "Golbat",
        "Oddish",
        "Gloom",
        "Vileplume",
        "Paras",
        "Parasect",
        "Venonat",
        "Venomoth",
        "Diglett",
        "Dugtrio",
        "Meowth",
        "Persian",
        "Psyduck",
        "Golduck",
        "Mankey",
        "Primeape",
        "Growlithe",
        "Arcanine",
        "Poliwag",
        "Poliwhirl",
        "Poliwrath",
        "Abra",
        "Kadabra",
        "Alakazam",
        "Machop",
        "Machoke",
        "Machamp",
        "Bellsprout",
        "Weepinbell",
        "Victreebel",
        "Tentacool",
        "Tentacruel",
        "Geodude",
        "Graveler",
        "Golem",
        "Ponyta",
        "Rapidash",
        "Slowpoke",
        "Slowbro",
        "Magnemite",
        "Magneton",
        "Farfetch'd",
        "Doduo",
        "Dodrio",
        "Seel",
        "Dewgong",
        "Grimer",
        "Muk",
        "Shellder",
        "Cloyster",
        "Gastly",
        "Haunter",
        "Gengar",
        "Onix",
        "Drowzee",
        "Hypno",
        "Krabby",
        "Kingler",
        "Voltorb",
        "Electrode",
        "Exeggcute",
        "Exeggutor",
        "Cubone",
        "Marowak",
        "Hitmonlee",
        "Hitmonchan",
        "Lickitung",
        "Koffing",
        "Weezing",
        "Rhyhorn",
        "Rhydon",
        "Chansey",
        "Tangela",
        "Kangaskhan",
        "Horsea",
        "Seadra",
        "Goldeen",
        "Seaking",
        "Staryu",
        "Starmie",
        "Mr. Mime",
        "Scyther",
        "Jynx",
        "Electabuzz",
        "Magmar",
        "Pinsir",
        "Tauros",
        "Magikarp",
        "Gyarados",
        "Lapras",
        "Ditto",
        "Eevee",
        "Vaporeon",
        "Jolteon",
        "Flareon",
        "Porygon",
        "Omanyte",
        "Omastar",
        "Kabuto",
        "Kabutops",
        "Aerodactyl",
        "Snorlax",
        "Articuno",
        "Zapdos",
        "Moltres",
        "Dratini",
        "Dragonair",
        "Dragonite",
        "Mewtwo",
        "Mew"
    ],
    "map": {
        "debug": false,
        "cacheTag": "1626058028",
        "north_direction": "lower-left",
        "controls": {
            "pan": true,
            "zoom": true,
            "spawn": true,
            "compass": true,
            "mapType": true,
            "overlays": true,
            "coordsBox": true
        }
    },
    "tilesets": [
        {
            "name": "Gen 1",
            "zoomLevels": 5,
            "defaultZoom": 2,
            "maxZoom": 5,
            "path": "1",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Bulbasaur",
            "last_rendertime": 2129127647,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                23,
                30,
                35
            ],
            "minZoom": 2,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 5,
            "defaultZoom": 2,
            "maxZoom": 5,
            "path": "2",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Ivysaur",
            "last_rendertime": 2126302490,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                181,
                51,
                36
            ],
            "minZoom": 2,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 6,
            "defaultZoom": 3,
            "maxZoom": 6,
            "path": "3",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Venusaur",
            "last_rendertime": 2145072396,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                463,
                74,
                35
            ],
            "minZoom": 3,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 6,
            "defaultZoom": 3,
            "maxZoom": 6,
            "path": "4",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Charmander",
            "last_rendertime": 2147448621,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                707,
                35,
                35
            ],
            "minZoom": 3,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 6,
            "defaultZoom": 3,
            "maxZoom": 6,
            "path": "5",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Charmeleon",
            "last_rendertime": 2132482054,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                845,
                44,
                36
            ],
            "minZoom": 3,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 7,
            "defaultZoom": 4,
            "maxZoom": 7,
            "path": "6",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Charizard",
            "last_rendertime": 2143362072,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                1104,
                90,
                35
            ],
            "minZoom": 4,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 7,
            "defaultZoom": 4,
            "maxZoom": 7,
            "path": "7",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Squirtle",
            "last_rendertime": 2130708214,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                1358,
                34,
                36
            ],
            "minZoom": 4,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 7,
            "defaultZoom": 4,
            "maxZoom": 7,
            "path": "8",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Wartortle",
            "last_rendertime": 2147471823,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                1492,
                41,
                36
            ],
            "minZoom": 4,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 7,
            "defaultZoom": 4,
            "maxZoom": 7,
            "path": "9",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Blastoise",
            "last_rendertime": 2126302490,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                1696,
                81,
                35
            ],
            "minZoom": 4,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 7,
            "defaultZoom": 4,
            "maxZoom": 7,
            "path": "10",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Caterpie",
            "last_rendertime": 1901279175,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                1882,
                25,
                35
            ],
            "minZoom": 4,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 7,
            "defaultZoom": 4,
            "maxZoom": 7,
            "path": "11",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Metapod",
            "last_rendertime": 2126302490,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                1965,
                31,
                36
            ],
            "minZoom": 4,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 8,
            "defaultZoom": 5,
            "maxZoom": 8,
            "path": "12",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Butterfree",
            "last_rendertime": 2146854783,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                2132,
                61,
                35
            ],
            "minZoom": 5,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 8,
            "defaultZoom": 5,
            "maxZoom": 8,
            "path": "13",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Weedle",
            "last_rendertime": 2139568540,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                2291,
                24,
                35
            ],
            "minZoom": 5,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 8,
            "defaultZoom": 5,
            "maxZoom": 8,
            "path": "14",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Kakuna",
            "last_rendertime": 2099821348,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                2370,
                31,
                35
            ],
            "minZoom": 5,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 8,
            "defaultZoom": 5,
            "maxZoom": 8,
            "path": "15",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Beedrill",
            "last_rendertime": 2112216343,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                2512,
                59,
                35
            ],
            "minZoom": 5,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 8,
            "defaultZoom": 5,
            "maxZoom": 8,
            "path": "16",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Pidgey",
            "last_rendertime": 2140919118,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                2697,
                26,
                35
            ],
            "minZoom": 5,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 8,
            "defaultZoom": 5,
            "maxZoom": 8,
            "path": "17",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Pidgeotto",
            "last_rendertime": 2146854783,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                2887,
                34,
                35
            ],
            "minZoom": 5,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 8,
            "defaultZoom": 5,
            "maxZoom": 8,
            "path": "18",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Pidgeot",
            "last_rendertime": 2146679181,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                3140,
                46,
                36
            ],
            "minZoom": 5,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 8,
            "defaultZoom": 5,
            "maxZoom": 8,
            "path": "19",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Rattata",
            "last_rendertime": 2138016385,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                3342,
                23,
                36
            ],
            "minZoom": 5,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 8,
            "defaultZoom": 5,
            "maxZoom": 8,
            "path": "20",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Raticate",
            "last_rendertime": 2120609202,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                3451,
                36,
                36
            ],
            "minZoom": 5,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 8,
            "defaultZoom": 5,
            "maxZoom": 8,
            "path": "21",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Spearow",
            "last_rendertime": 2142987059,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                3596,
                27,
                35
            ],
            "minZoom": 5,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 8,
            "defaultZoom": 5,
            "maxZoom": 8,
            "path": "22",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Fearow",
            "last_rendertime": 2146854783,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                3829,
                34,
                35
            ],
            "minZoom": 5,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 8,
            "defaultZoom": 5,
            "maxZoom": 8,
            "path": "23",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Ekans",
            "last_rendertime": 2098336209,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                4030,
                33,
                35
            ],
            "minZoom": 5,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 9,
            "defaultZoom": 6,
            "maxZoom": 9,
            "path": "24",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Arbok",
            "last_rendertime": 2133320248,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                4159,
                55,
                35
            ],
            "minZoom": 6,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 9,
            "defaultZoom": 6,
            "maxZoom": 9,
            "path": "25",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Pikachu",
            "last_rendertime": 2046323633,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                4288,
                36,
                36
            ],
            "minZoom": 6,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 9,
            "defaultZoom": 6,
            "maxZoom": 9,
            "path": "26",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Raichu",
            "last_rendertime": 2115698522,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                4419,
                42,
                35
            ],
            "minZoom": 6,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 9,
            "defaultZoom": 6,
            "maxZoom": 9,
            "path": "27",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Sandshrew",
            "last_rendertime": 2117382608,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                4555,
                30,
                36
            ],
            "minZoom": 6,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 9,
            "defaultZoom": 6,
            "maxZoom": 9,
            "path": "28",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Sandslash",
            "last_rendertime": 2123799695,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                4687,
                42,
                35
            ],
            "minZoom": 6,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 9,
            "defaultZoom": 6,
            "maxZoom": 9,
            "path": "29",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "NidoranF",
            "last_rendertime": 2133719758,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                4818,
                27,
                36
            ],
            "minZoom": 6,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 9,
            "defaultZoom": 6,
            "maxZoom": 9,
            "path": "30",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Nidorina",
            "last_rendertime": 2078832523,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                4937,
                38,
                35
            ],
            "minZoom": 6,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 9,
            "defaultZoom": 6,
            "maxZoom": 9,
            "path": "31",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Nidoqueen",
            "last_rendertime": 2147138119,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                5122,
                64,
                35
            ],
            "minZoom": 6,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 9,
            "defaultZoom": 6,
            "maxZoom": 9,
            "path": "32",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "NidoranM",
            "last_rendertime": 2146952191,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                5318,
                26,
                36
            ],
            "minZoom": 6,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 9,
            "defaultZoom": 6,
            "maxZoom": 9,
            "path": "33",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Nidorino",
            "last_rendertime": 2111383193,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                5463,
                39,
                36
            ],
            "minZoom": 6,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 9,
            "defaultZoom": 6,
            "maxZoom": 9,
            "path": "34",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Nidoking",
            "last_rendertime": 2144095368,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                5681,
                73,
                35
            ],
            "minZoom": 6,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 9,
            "defaultZoom": 6,
            "maxZoom": 9,
            "path": "35",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Clefairy",
            "last_rendertime": 2142238175,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                5887,
                32,
                36
            ],
            "minZoom": 6,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 9,
            "defaultZoom": 6,
            "maxZoom": 9,
            "path": "36",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Clefable",
            "last_rendertime": 2138519751,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                6052,
                46,
                36
            ],
            "minZoom": 6,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 9,
            "defaultZoom": 6,
            "maxZoom": 9,
            "path": "37",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Vulpix",
            "last_rendertime": 2021299868,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                6221,
                31,
                35
            ],
            "minZoom": 6,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 9,
            "defaultZoom": 6,
            "maxZoom": 9,
            "path": "38",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Ninetales",
            "last_rendertime": 2145751761,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                6439,
                57,
                35
            ],
            "minZoom": 6,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 9,
            "defaultZoom": 6,
            "maxZoom": 9,
            "path": "39",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Jigglypuff",
            "last_rendertime": 2146440889,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                6649,
                29,
                36
            ],
            "minZoom": 6,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 9,
            "defaultZoom": 6,
            "maxZoom": 9,
            "path": "40",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Wigglytuff",
            "last_rendertime": 2145705955,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                6799,
                50,
                36
            ],
            "minZoom": 6,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 9,
            "defaultZoom": 6,
            "maxZoom": 9,
            "path": "41",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Zubat",
            "last_rendertime": 2096647808,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                6972,
                36,
                36
            ],
            "minZoom": 6,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 9,
            "defaultZoom": 6,
            "maxZoom": 9,
            "path": "42",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Golbat",
            "last_rendertime": 2115004391,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                7209,
                44,
                35
            ],
            "minZoom": 6,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 9,
            "defaultZoom": 6,
            "maxZoom": 9,
            "path": "43",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Oddish",
            "last_rendertime": 2133971286,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                7432,
                36,
                36
            ],
            "minZoom": 6,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 9,
            "defaultZoom": 6,
            "maxZoom": 9,
            "path": "44",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Gloom",
            "last_rendertime": 2131162874,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                7609,
                35,
                36
            ],
            "minZoom": 6,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 9,
            "defaultZoom": 6,
            "maxZoom": 9,
            "path": "45",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Vileplume",
            "last_rendertime": 2143362072,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                7808,
                50,
                35
            ],
            "minZoom": 6,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 9,
            "defaultZoom": 6,
            "maxZoom": 9,
            "path": "46",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Paras",
            "last_rendertime": 2099821348,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                7990,
                16,
                35
            ],
            "minZoom": 6,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 9,
            "defaultZoom": 6,
            "maxZoom": 9,
            "path": "47",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Parasect",
            "last_rendertime": 2146953847,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                8094,
                38,
                36
            ],
            "minZoom": 6,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 10,
            "defaultZoom": 7,
            "maxZoom": 10,
            "path": "48",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Venonat",
            "last_rendertime": 2121739520,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                8201,
                35,
                35
            ],
            "minZoom": 7,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 10,
            "defaultZoom": 7,
            "maxZoom": 10,
            "path": "49",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Venomoth",
            "last_rendertime": 2145335296,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                8366,
                46,
                36
            ],
            "minZoom": 7,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 10,
            "defaultZoom": 7,
            "maxZoom": 10,
            "path": "50",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Diglett",
            "last_rendertime": 2133685917,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                8537,
                24,
                36
            ],
            "minZoom": 7,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 10,
            "defaultZoom": 7,
            "maxZoom": 10,
            "path": "51",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Dugtrio",
            "last_rendertime": 2145335296,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                8673,
                34,
                36
            ],
            "minZoom": 7,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 10,
            "defaultZoom": 7,
            "maxZoom": 10,
            "path": "52",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Meowth",
            "last_rendertime": 2141898453,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                8828,
                39,
                35
            ],
            "minZoom": 7,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 10,
            "defaultZoom": 7,
            "maxZoom": 10,
            "path": "53",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Persian",
            "last_rendertime": 2143339499,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                8969,
                42,
                35
            ],
            "minZoom": 7,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 10,
            "defaultZoom": 7,
            "maxZoom": 10,
            "path": "54",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Psyduck",
            "last_rendertime": 2132895455,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                9123,
                42,
                36
            ],
            "minZoom": 7,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 10,
            "defaultZoom": 7,
            "maxZoom": 10,
            "path": "55",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Golduck",
            "last_rendertime": 2108934227,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                9300,
                61,
                36
            ],
            "minZoom": 7,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 10,
            "defaultZoom": 7,
            "maxZoom": 10,
            "path": "56",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Mankey",
            "last_rendertime": 2146955522,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                9486,
                42,
                35
            ],
            "minZoom": 7,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 10,
            "defaultZoom": 7,
            "maxZoom": 10,
            "path": "57",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Primeape",
            "last_rendertime": 2147450066,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                9706,
                59,
                36
            ],
            "minZoom": 7,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 10,
            "defaultZoom": 7,
            "maxZoom": 10,
            "path": "58",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Growlithe",
            "last_rendertime": 2124418808,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                9891,
                39,
                36
            ],
            "minZoom": 7,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 10,
            "defaultZoom": 7,
            "maxZoom": 10,
            "path": "59",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Arcanine",
            "last_rendertime": 2145335296,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                10027,
                58,
                35
            ],
            "minZoom": 7,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 10,
            "defaultZoom": 7,
            "maxZoom": 10,
            "path": "60",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Poliwag",
            "last_rendertime": 2145335296,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                10168,
                26,
                36
            ],
            "minZoom": 7,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 10,
            "defaultZoom": 7,
            "maxZoom": 10,
            "path": "61",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Poliwhirl",
            "last_rendertime": 2137517645,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                10344,
                46,
                35
            ],
            "minZoom": 7,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 10,
            "defaultZoom": 7,
            "maxZoom": 10,
            "path": "62",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Poliwrath",
            "last_rendertime": 2146610817,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                10647,
                66,
                35
            ],
            "minZoom": 7,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 10,
            "defaultZoom": 7,
            "maxZoom": 10,
            "path": "63",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Abra",
            "last_rendertime": 2139108200,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                10887,
                37,
                35
            ],
            "minZoom": 7,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 10,
            "defaultZoom": 7,
            "maxZoom": 10,
            "path": "64",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Kadabra",
            "last_rendertime": 2133702301,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                11060,
                46,
                36
            ],
            "minZoom": 7,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 10,
            "defaultZoom": 7,
            "maxZoom": 10,
            "path": "65",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Alakazam",
            "last_rendertime": 2147435981,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                11281,
                57,
                35
            ],
            "minZoom": 7,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 10,
            "defaultZoom": 7,
            "maxZoom": 10,
            "path": "66",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Machop",
            "last_rendertime": 2144328333,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                11471,
                39,
                35
            ],
            "minZoom": 7,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 10,
            "defaultZoom": 7,
            "maxZoom": 10,
            "path": "67",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Machoke",
            "last_rendertime": 2077989243,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                11643,
                51,
                36
            ],
            "minZoom": 7,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 10,
            "defaultZoom": 7,
            "maxZoom": 10,
            "path": "68",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Machamp",
            "last_rendertime": 2133702301,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                11884,
                69,
                36
            ],
            "minZoom": 7,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 10,
            "defaultZoom": 7,
            "maxZoom": 10,
            "path": "69",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Bellsprout",
            "last_rendertime": 2077989243,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                12096,
                29,
                36
            ],
            "minZoom": 7,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 10,
            "defaultZoom": 7,
            "maxZoom": 10,
            "path": "70",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Weepinbell",
            "last_rendertime": 2066289938,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                12239,
                39,
                36
            ],
            "minZoom": 7,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 10,
            "defaultZoom": 7,
            "maxZoom": 10,
            "path": "71",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Victreebel",
            "last_rendertime": 2128913247,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                12453,
                44,
                35
            ],
            "minZoom": 7,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 10,
            "defaultZoom": 7,
            "maxZoom": 10,
            "path": "72",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Tentacool",
            "last_rendertime": 1880784291,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                12633,
                38,
                36
            ],
            "minZoom": 7,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 10,
            "defaultZoom": 7,
            "maxZoom": 10,
            "path": "73",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Tentacruel",
            "last_rendertime": 2133685917,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                12782,
                62,
                36
            ],
            "minZoom": 7,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 10,
            "defaultZoom": 7,
            "maxZoom": 10,
            "path": "74",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Geodude",
            "last_rendertime": 2145245055,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                12984,
                27,
                36
            ],
            "minZoom": 7,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 10,
            "defaultZoom": 7,
            "maxZoom": 10,
            "path": "75",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Graveler",
            "last_rendertime": 2137751673,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                13192,
                45,
                35
            ],
            "minZoom": 7,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 10,
            "defaultZoom": 7,
            "maxZoom": 10,
            "path": "76",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Golem",
            "last_rendertime": 2124973737,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                13455,
                57,
                35
            ],
            "minZoom": 7,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 10,
            "defaultZoom": 7,
            "maxZoom": 10,
            "path": "77",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Ponyta",
            "last_rendertime": 2078871175,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                13656,
                45,
                35
            ],
            "minZoom": 7,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 10,
            "defaultZoom": 7,
            "maxZoom": 10,
            "path": "78",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Rapidash",
            "last_rendertime": 2118813712,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                13782,
                59,
                36
            ],
            "minZoom": 7,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 10,
            "defaultZoom": 7,
            "maxZoom": 10,
            "path": "79",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Slowpoke",
            "last_rendertime": 2056688271,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                13928,
                31,
                36
            ],
            "minZoom": 7,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 10,
            "defaultZoom": 7,
            "maxZoom": 10,
            "path": "80",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Slowbro",
            "last_rendertime": 2146613407,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                14080,
                58,
                36
            ],
            "minZoom": 7,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 10,
            "defaultZoom": 7,
            "maxZoom": 10,
            "path": "81",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Magnemite",
            "last_rendertime": 2143421081,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                14243,
                26,
                36
            ],
            "minZoom": 7,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 10,
            "defaultZoom": 7,
            "maxZoom": 10,
            "path": "82",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Magneton",
            "last_rendertime": 2132482054,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                14420,
                40,
                35
            ],
            "minZoom": 7,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 10,
            "defaultZoom": 7,
            "maxZoom": 10,
            "path": "83",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Farfetch'd",
            "last_rendertime": 2137751673,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                14605,
                36,
                35
            ],
            "minZoom": 7,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 10,
            "defaultZoom": 7,
            "maxZoom": 10,
            "path": "84",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Doduo",
            "last_rendertime": 2091207466,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                14767,
                60,
                35
            ],
            "minZoom": 7,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 10,
            "defaultZoom": 7,
            "maxZoom": 10,
            "path": "85",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Dodrio",
            "last_rendertime": 2095340010,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                14972,
                77,
                36
            ],
            "minZoom": 7,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 10,
            "defaultZoom": 7,
            "maxZoom": 10,
            "path": "86",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Seel",
            "last_rendertime": 2137751673,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                15198,
                36,
                36
            ],
            "minZoom": 7,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 10,
            "defaultZoom": 7,
            "maxZoom": 10,
            "path": "87",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Dewgong",
            "last_rendertime": 2146066854,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                15417,
                53,
                35
            ],
            "minZoom": 7,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 10,
            "defaultZoom": 7,
            "maxZoom": 10,
            "path": "88",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Grimer",
            "last_rendertime": 2146955384,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                15634,
                48,
                36
            ],
            "minZoom": 7,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 10,
            "defaultZoom": 7,
            "maxZoom": 10,
            "path": "89",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Muk",
            "last_rendertime": 2146589268,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                15872,
                66,
                36
            ],
            "minZoom": 7,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 10,
            "defaultZoom": 7,
            "maxZoom": 10,
            "path": "90",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Shellder",
            "last_rendertime": 2144596287,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                16082,
                18,
                35
            ],
            "minZoom": 7,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 10,
            "defaultZoom": 7,
            "maxZoom": 10,
            "path": "91",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Cloyster",
            "last_rendertime": 2132482054,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                16205,
                50,
                35
            ],
            "minZoom": 7,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 11,
            "defaultZoom": 8,
            "maxZoom": 11,
            "path": "92",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Gastly",
            "last_rendertime": 2045769223,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                16348,
                34,
                36
            ],
            "minZoom": 8,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 11,
            "defaultZoom": 8,
            "maxZoom": 11,
            "path": "93",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Haunter",
            "last_rendertime": 2086114951,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                16511,
                38,
                36
            ],
            "minZoom": 8,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 11,
            "defaultZoom": 8,
            "maxZoom": 11,
            "path": "94",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Gengar",
            "last_rendertime": 2115698522,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                16696,
                52,
                35
            ],
            "minZoom": 8,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 11,
            "defaultZoom": 8,
            "maxZoom": 11,
            "path": "95",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Onix",
            "last_rendertime": 2146591927,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                16930,
                126,
                36
            ],
            "minZoom": 8,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 11,
            "defaultZoom": 8,
            "maxZoom": 11,
            "path": "96",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Drowzee",
            "last_rendertime": 2142223720,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                17161,
                50,
                35
            ],
            "minZoom": 8,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 11,
            "defaultZoom": 8,
            "maxZoom": 11,
            "path": "97",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Hypno",
            "last_rendertime": 2077724454,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                17385,
                60,
                35
            ],
            "minZoom": 8,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 11,
            "defaultZoom": 8,
            "maxZoom": 11,
            "path": "98",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Krabby",
            "last_rendertime": 2088013299,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                17599,
                32,
                35
            ],
            "minZoom": 8,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 11,
            "defaultZoom": 8,
            "maxZoom": 11,
            "path": "99",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Kingler",
            "last_rendertime": 2113563569,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                17782,
                54,
                36
            ],
            "minZoom": 8,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 11,
            "defaultZoom": 8,
            "maxZoom": 11,
            "path": "100",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Voltorb",
            "last_rendertime": 2115698266,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                17946,
                26,
                36
            ],
            "minZoom": 8,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 11,
            "defaultZoom": 8,
            "maxZoom": 11,
            "path": "101",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Electrode",
            "last_rendertime": 2145385063,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                18064,
                34,
                36
            ],
            "minZoom": 8,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 11,
            "defaultZoom": 8,
            "maxZoom": 11,
            "path": "102",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Exeggcute",
            "last_rendertime": 2124993652,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                18200,
                18,
                36
            ],
            "minZoom": 8,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 11,
            "defaultZoom": 8,
            "maxZoom": 11,
            "path": "103",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Exeggutor",
            "last_rendertime": 2145114733,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                18378,
                62,
                35
            ],
            "minZoom": 8,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 11,
            "defaultZoom": 8,
            "maxZoom": 11,
            "path": "104",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Cubone",
            "last_rendertime": 2071735786,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                18535,
                27,
                35
            ],
            "minZoom": 8,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 11,
            "defaultZoom": 8,
            "maxZoom": 11,
            "path": "105",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Marowak",
            "last_rendertime": 2130637291,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                18645,
                41,
                35
            ],
            "minZoom": 8,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 11,
            "defaultZoom": 8,
            "maxZoom": 11,
            "path": "106",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Hitmonlee",
            "last_rendertime": 2058615864,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                18819,
                46,
                35
            ],
            "minZoom": 8,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 11,
            "defaultZoom": 8,
            "maxZoom": 11,
            "path": "107",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Hitmonchan",
            "last_rendertime": 2146296772,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                19008,
                47,
                36
            ],
            "minZoom": 8,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 11,
            "defaultZoom": 8,
            "maxZoom": 11,
            "path": "108",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Lickitung",
            "last_rendertime": 2142953415,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                19187,
                48,
                36
            ],
            "minZoom": 8,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 11,
            "defaultZoom": 8,
            "maxZoom": 11,
            "path": "109",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Koffing",
            "last_rendertime": 2134886271,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                19376,
                39,
                36
            ],
            "minZoom": 8,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 11,
            "defaultZoom": 8,
            "maxZoom": 11,
            "path": "110",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Weezing",
            "last_rendertime": 2137751673,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                19582,
                57,
                36
            ],
            "minZoom": 8,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 11,
            "defaultZoom": 8,
            "maxZoom": 11,
            "path": "111",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Rhyhorn",
            "last_rendertime": 2100321546,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                19839,
                58,
                35
            ],
            "minZoom": 8,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 11,
            "defaultZoom": 8,
            "maxZoom": 11,
            "path": "112",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Rhydon",
            "last_rendertime": 2137751673,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                20132,
                87,
                36
            ],
            "minZoom": 8,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 11,
            "defaultZoom": 8,
            "maxZoom": 11,
            "path": "113",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Chansey",
            "last_rendertime": 2128019699,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                20420,
                44,
                36
            ],
            "minZoom": 8,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 11,
            "defaultZoom": 8,
            "maxZoom": 11,
            "path": "114",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Tangela",
            "last_rendertime": 2112344951,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                20696,
                40,
                36
            ],
            "minZoom": 8,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 11,
            "defaultZoom": 8,
            "maxZoom": 11,
            "path": "115",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Kangaskhan",
            "last_rendertime": 2135089262,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                20915,
                85,
                36
            ],
            "minZoom": 8,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 11,
            "defaultZoom": 8,
            "maxZoom": 11,
            "path": "116",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Horsea",
            "last_rendertime": 2009097591,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                21110,
                24,
                35
            ],
            "minZoom": 8,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 11,
            "defaultZoom": 8,
            "maxZoom": 11,
            "path": "117",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Seadra",
            "last_rendertime": 2147466109,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                21234,
                49,
                35
            ],
            "minZoom": 8,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 11,
            "defaultZoom": 8,
            "maxZoom": 11,
            "path": "118",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Goldeen",
            "last_rendertime": 2147071388,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                21386,
                24,
                36
            ],
            "minZoom": 8,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 11,
            "defaultZoom": 8,
            "maxZoom": 11,
            "path": "119",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Seaking",
            "last_rendertime": 2087877638,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                21527,
                42,
                36
            ],
            "minZoom": 8,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 11,
            "defaultZoom": 8,
            "maxZoom": 11,
            "path": "120",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Staryu",
            "last_rendertime": 2117078079,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                21657,
                34,
                36
            ],
            "minZoom": 8,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 11,
            "defaultZoom": 8,
            "maxZoom": 11,
            "path": "121",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Starmie",
            "last_rendertime": 2105566296,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                21813,
                46,
                36
            ],
            "minZoom": 8,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 11,
            "defaultZoom": 8,
            "maxZoom": 11,
            "path": "122",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Mr. Mime",
            "last_rendertime": 2144968317,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                22010,
                49,
                36
            ],
            "minZoom": 8,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 11,
            "defaultZoom": 8,
            "maxZoom": 11,
            "path": "123",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Scyther",
            "last_rendertime": 2135735826,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                22229,
                66,
                36
            ],
            "minZoom": 8,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 11,
            "defaultZoom": 8,
            "maxZoom": 11,
            "path": "124",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Jynx",
            "last_rendertime": 2142688183,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                22444,
                39,
                36
            ],
            "minZoom": 8,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 11,
            "defaultZoom": 8,
            "maxZoom": 11,
            "path": "125",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Electabuzz",
            "last_rendertime": 2137751673,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                22623,
                51,
                36
            ],
            "minZoom": 8,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 11,
            "defaultZoom": 8,
            "maxZoom": 11,
            "path": "126",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Magmar",
            "last_rendertime": 2133685917,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                22833,
                60,
                36
            ],
            "minZoom": 8,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 11,
            "defaultZoom": 8,
            "maxZoom": 11,
            "path": "127",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Pinsir",
            "last_rendertime": 2139058749,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                23055,
                48,
                36
            ],
            "minZoom": 8,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 11,
            "defaultZoom": 8,
            "maxZoom": 11,
            "path": "128",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Tauros",
            "last_rendertime": 2147433787,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                23290,
                52,
                36
            ],
            "minZoom": 8,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 11,
            "defaultZoom": 8,
            "maxZoom": 11,
            "path": "129",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Magikarp",
            "last_rendertime": 2139111129,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                23511,
                36,
                35
            ],
            "minZoom": 8,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 11,
            "defaultZoom": 8,
            "maxZoom": 11,
            "path": "130",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Gyarados",
            "last_rendertime": 2141243453,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                23716,
                112,
                36
            ],
            "minZoom": 8,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 11,
            "defaultZoom": 8,
            "maxZoom": 11,
            "path": "131",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Lapras",
            "last_rendertime": 2146168543,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                24017,
                80,
                36
            ],
            "minZoom": 8,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 11,
            "defaultZoom": 8,
            "maxZoom": 11,
            "path": "132",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Ditto",
            "last_rendertime": 2142829231,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                24413,
                21,
                36
            ],
            "minZoom": 8,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 11,
            "defaultZoom": 8,
            "maxZoom": 11,
            "path": "133",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Eevee",
            "last_rendertime": 2147125054,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                24539,
                41,
                35
            ],
            "minZoom": 8,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 11,
            "defaultZoom": 8,
            "maxZoom": 11,
            "path": "134",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Vaporeon",
            "last_rendertime": 2143370392,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                24720,
                53,
                36
            ],
            "minZoom": 8,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 11,
            "defaultZoom": 8,
            "maxZoom": 11,
            "path": "135",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Jolteon",
            "last_rendertime": 2129126885,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                24883,
                49,
                35
            ],
            "minZoom": 8,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 11,
            "defaultZoom": 8,
            "maxZoom": 11,
            "path": "136",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Flareon",
            "last_rendertime": 2145295088,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                25065,
                47,
                36
            ],
            "minZoom": 8,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 11,
            "defaultZoom": 8,
            "maxZoom": 11,
            "path": "137",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Porygon",
            "last_rendertime": 2146106494,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                25241,
                34,
                36
            ],
            "minZoom": 8,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 11,
            "defaultZoom": 8,
            "maxZoom": 11,
            "path": "138",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Omanyte",
            "last_rendertime": 2132482054,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                25383,
                35,
                36
            ],
            "minZoom": 8,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 11,
            "defaultZoom": 8,
            "maxZoom": 11,
            "path": "139",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Omastar",
            "last_rendertime": 2113364279,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                25537,
                41,
                36
            ],
            "minZoom": 8,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 11,
            "defaultZoom": 8,
            "maxZoom": 11,
            "path": "140",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Kabuto",
            "last_rendertime": 2038307582,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                25682,
                18,
                36
            ],
            "minZoom": 8,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 11,
            "defaultZoom": 8,
            "maxZoom": 11,
            "path": "141",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Kabutops",
            "last_rendertime": 2137797277,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                25819,
                50,
                35
            ],
            "minZoom": 8,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 11,
            "defaultZoom": 8,
            "maxZoom": 11,
            "path": "142",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Aerodactyl",
            "last_rendertime": 2146939688,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                26071,
                48,
                35
            ],
            "minZoom": 8,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 11,
            "defaultZoom": 8,
            "maxZoom": 11,
            "path": "143",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Snorlax",
            "last_rendertime": 2146355496,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                26411,
                78,
                36
            ],
            "minZoom": 8,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 11,
            "defaultZoom": 8,
            "maxZoom": 11,
            "path": "144",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Articuno",
            "last_rendertime": 2142436733,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                26756,
                56,
                36
            ],
            "minZoom": 8,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 11,
            "defaultZoom": 8,
            "maxZoom": 11,
            "path": "145",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Zapdos",
            "last_rendertime": 2144625503,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                27141,
                78,
                35
            ],
            "minZoom": 8,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 11,
            "defaultZoom": 8,
            "maxZoom": 11,
            "path": "146",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Moltres",
            "last_rendertime": 2146752632,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                27542,
                98,
                36
            ],
            "minZoom": 8,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 11,
            "defaultZoom": 8,
            "maxZoom": 11,
            "path": "147",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Dratini",
            "last_rendertime": 2137686149,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                27860,
                55,
                36
            ],
            "minZoom": 8,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 11,
            "defaultZoom": 8,
            "maxZoom": 11,
            "path": "148",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Dragonair",
            "last_rendertime": 2137686149,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                28069,
                65,
                36
            ],
            "minZoom": 8,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 11,
            "defaultZoom": 8,
            "maxZoom": 11,
            "path": "149",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Dragonite",
            "last_rendertime": 2145778609,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                28338,
                93,
                35
            ],
            "minZoom": 8,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 11,
            "defaultZoom": 8,
            "maxZoom": 11,
            "path": "150",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Mewtwo",
            "last_rendertime": 2137751621,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                28630,
                77,
                36
            ],
            "minZoom": 8,
            "spawn": false,
            "north_direction": 1
        },
        {
            "name": "Gen 1",
            "zoomLevels": 11,
            "defaultZoom": 8,
            "maxZoom": 11,
            "path": "151",
            "base": "",
            "bgcolor": "#1a1a1a",
            "world": "Mew",
            "last_rendertime": 2108444125,
            "imgextension": "png",
            "isOverlay": false,
            "poititle": "Markers",
            "showlocationmarker": false,
            "center": [
                28920,
                23,
                40
            ],
            "minZoom": 8,
            "spawn": false,
            "north_direction": 1
        }
    ]
};
